version: '3.8'

services:
  api:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-localhost}/smartinsight-api:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
      - qdrant
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT:-Production}
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=smartinsight;Username=${DB_USER:-postgres};Password=${DB_PASSWORD:-postgres}
      - Qdrant__Endpoint=http://qdrant:6333
      - Ollama__BaseUrl=${OLLAMA_URL:-http://ollama:11434}
    networks:
      - smartinsight-network
    volumes:
      - api-logs:/app/logs

  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=smartinsight
    ports:
      - "5432:5432"
    networks:
      - smartinsight-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"
    networks:
      - smartinsight-network
    volumes:
      - qdrant-data:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    restart: always
    ports:
      - "11434:11434"
    networks:
      - smartinsight-network
    volumes:
      - ollama-models:/root/.ollama

  seq:
    image: datalust/seq:latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8081:80"
    networks:
      - smartinsight-network
    volumes:
      - seq-data:/data

networks:
  smartinsight-network:
    driver: bridge

volumes:
  postgres-data:
  qdrant-data:
  ollama-models:
  seq-data:
  api-logs: 