version: '3.8'

services:
  api:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-localhost}/smartinsight-api:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_started
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT:-Production}
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=smartinsight;Username=${DB_USER:-postgres};Password=${DB_PASSWORD:-postgres}
      - Qdrant__Endpoint=http://qdrant:6333
      - Ollama__BaseUrl=${OLLAMA_URL:-http://ollama:11434}
    networks:
      - smartinsight-network
    volumes:
      - api-logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=smartinsight
    ports:
      - "5432:5432"
    networks:
      - smartinsight-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./scripts/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d smartinsight"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: ["postgres", "-c", "row_security=on", "-c", "shared_preload_libraries=pg_stat_statements"]

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"
    networks:
      - smartinsight-network
    volumes:
      - qdrant-data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  ollama:
    image: ollama/ollama:latest
    restart: always
    ports:
      - "11434:11434"
    networks:
      - smartinsight-network
    volumes:
      - ollama-models:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  seq:
    image: datalust/seq:latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8081:80"
    networks:
      - smartinsight-network
    volumes:
      - seq-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  smartinsight-network:
    driver: bridge

volumes:
  postgres-data:
  qdrant-data:
  ollama-models:
  seq-data:
  api-logs: 