# Qdrant Configuration File
# This configuration is optimized for tenant isolation and vector similarity search

log_level: INFO

storage:
  # Storage persistence path
  storage_path: ./storage

  # Engine type to use for vector search - HNSW offers superior performance
  vector_data:
    hnsw_config:  # Parameters for HNSW index
      m: 16  # Number of edges per node in the index graph
      ef_construct: 100  # Size of the dynamic candidate list during construction
      full_scan_threshold: 10000  # Threshold for switching to full scan on small segments

  # Optimistic concurrency control for concurrent operations
  optimizers:
    deleted_threshold: 0.2  # Threshold ratio for deleting to trigger index optimization
    vacuum_min_vector_number: 1000  # Minimal number of vectors for optimization
    default_segment_number: 2  # Default number of segments for storage
    max_segment_size: 50000  # Maximum size of segment in vectors before it gets split
    memmap_threshold: 500000  # Minimal number of vectors to use memmap
    indexing_threshold: 20000  # Minimal number of vectors for parallel indexing
    flush_interval_sec: 60  # Interval between forced flushes on disk

  # Persistence and WAL settings
  wal:
    wal_capacity_mb: 32  # Size of the Write-Ahead-Log in megabytes
    wal_segments_ahead: 2  # Number of segments to create ahead of time

# Service settings
service:
  host: 0.0.0.0
  port: 6333
  http_port: 6334
  enable_tls: false  # Set to true with proper certificates for production use

# Limits for collection operations
limits:
  payload_bytes_limit: 16777216  # Limit payload bytes size per single request (16 MB)
  vectors_batch_size: 1000  # Maximum size of a vector batch in a single request
  max_segment_size_kb: 10485760  # Maximum size of a segment before it is split (10 GB)

cluster:
  enabled: false  # Set to true for multiple node deployments
  
# Telemetry collection - anonymized usage stats
telemetry:
  disabled: false  # Set to true to disable telemetry

# Configure periodic jobs
snapshots:
  enabled: true  # Enable periodic backups
  interval_sec: 7200  # Backup every 2 hours 